### ISSUE TITLE
Running docker jobmanager-1 automatically stops

### ISSUE THREAD

**Issue by aLIEzsss4** [chainbase-labs/manuscript-core#19]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Environment

Docker Engine
v27.2.0

### Steps to reproduce

>2024-10-22 13:56:53 Starting Job Manager
2024-10-22 13:57:02 2024-10-22 05:57:02,894 INFO  org.apache.pekko.remote.RemoteActorRefProvider$RemotingTerminator [] - Shutting down remote daemon.
2024-10-22 13:57:02 2024-10-22 05:57:02,895 INFO  org.apache.pekko.remote.RemoteActorRefProvider$RemotingTerminator [] - Remote daemon shut down; proceeding with flushing remote transports.
2024-10-22 13:57:02 2024-10-22 05:57:02,896 INFO  org.apache.pekko.remote.RemoteActorRefProvider$RemotingTerminator [] - Remote daemon shut down; proceeding with flushing remote transports.
2024-10-22 13:57:02 2024-10-22 05:57:02,948 INFO  org.apache.pekko.remote.RemoteActorRefProvider$RemotingTerminator [] - Remoting shut down.
2024-10-22 13:57:02 2024-10-22 05:57:02,961 INFO  org.apache.pekko.remote.RemoteActorRefProvider$RemotingTerminator [] - Remoting shut down.
2024-10-22 13:57:02 2024-10-22 05:57:02,979 INFO  org.apache.flink.runtime.rpc.pekko.PekkoRpcService           [] - Stopped Pekko RPC service.
2024-10-22 13:57:02 2024-10-22 05:57:02,987 INFO  org.apache.flink.runtime.rpc.pekko.PekkoRpcService           [] - Stopped Pekko RPC service.
2024-10-22 13:57:02 2024-10-22 05:57:02,987 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Terminating cluster entrypoint process StandaloneApplicationClusterEntryPoint with exit code 1445.
2024-10-22 13:57:02 WARNING: An illegal reflective access operation has occurred
2024-10-22 13:57:02 WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/opt/flink/tmp/flink-rpc-akka6103283f-2c58-41a0-90c9-fda685b7f490.jar) to method java.nio.DirectByteBuffer.cleaner()
2024-10-22 13:57:02 WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
2024-10-22 13:57:02 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2024-10-22 13:57:02 WARNING: All illegal access operations will be denied in a future release

**Comment by lxcong** [comment]
could you please provide the specific "manuscript.yaml"

**Comment by aLIEzsss4** [comment]
```
name: demo
specVersion: v0.1.0
parallelism: 1

sources:
  - name: ethereum_transactions
    type: dataset
    dataset: ethereum.transactions

transforms:
  - name: ethereum_transactions_transform
    sql: >
      Select * From ethereum_transactions

sinks:
  - name: ethereum_transactions_sink  
    type: postgres
    from: ethereum_transactions_transform
    database: ethereum
    schema: public
    table: transactions
    primary_key: block_number
    config: 
      host: postgres
      port: 5432
      username: postgres
      password: postgres
```
